// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `active_wallet`, `changes`, `ensure_enabled`, `lifecycle_lock`, `load_trade`, `notify`, `now_secs`, `proof_store_path`, `same_mint`, `sibling_store_path`, `snapshot`, `wallet_lock`

/// Connect the wallet to the mint the active node pins, unless already connected.
///
/// Lazy by design: nothing connects at startup, so a Lightning user never opens
/// a proof store or contacts a mint. Repeat calls are cheap — an already
/// connected wallet is returned as is rather than reconnected.
///
/// **Errors**: `CashuNotEnabled` when the node is not a usable Cashu node,
/// `NoIdentity` before an identity is loaded, `CashuNoMnemonic` for an
/// nsec-imported identity (there is no seed to derive), plus the markers from
/// [`CashuWallet::connect`].
Future<CashuWalletStatus> cashuConnect() =>
    RustLib.instance.api.crateApiCashuCashuConnect();

/// Current wallet status. Safe to call on any node — a Lightning node simply
/// reports "not connected".
Future<CashuWalletStatus> cashuStatus() =>
    RustLib.instance.api.crateApiCashuCashuStatus();

/// Spendable balance in satoshis.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`.
Future<BigInt> cashuGetBalance() =>
    RustLib.instance.api.crateApiCashuCashuGetBalance();

/// Redeem an encoded Cashu token into the wallet, returning the amount received.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`, `CashuReceiveFailed`
/// (wrong mint, already spent, malformed).
Future<BigInt> cashuReceiveToken({required String encoded}) =>
    RustLib.instance.api.crateApiCashuCashuReceiveToken(encoded: encoded);

/// Export `amount_sats` from the wallet as an encoded token.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`, `CashuAmountZero`,
/// `CashuSendFailed` (insufficient funds included).
Future<String> cashuCreateToken({required BigInt amountSats}) =>
    RustLib.instance.api.crateApiCashuCashuCreateToken(amountSats: amountSats);

/// Reconcile the proof store with the mint: proofs the mint reports spent are
/// forgotten, and the new balance is broadcast.
///
/// **Returns nothing on purpose.** It reclaims neither an unredeemed token of
/// ours nor the proofs of a half-finished send — cdk's state check cannot see
/// either — so there is no "reclaimed N sat" to report and C2 does not pretend
/// otherwise; see [`CashuWallet::sweep_spent_proofs`]. Getting an abandoned
/// token back is phase C10.
///
/// **Errors**: `CashuNotEnabled`, `CashuNotConnected`, `CashuMintChanged`.
Future<void> cashuSweepSpentProofs() =>
    RustLib.instance.api.crateApiCashuCashuSweepSpentProofs();

/// Drop the in-memory wallet. Proofs stay on disk — this is a disconnect, not a
/// wipe. Called when the active node changes, so a wallet bound to one node's
/// mint never serves another's.
Future<void> cashuDisconnect() =>
    RustLib.instance.api.crateApiCashuCashuDisconnect();

/// What the seller is about to lock, so the UI can show it before they commit.
///
/// Computed rather than taken from the daemon: the daemon states the amount in
/// the escrow request, but the **fee** is derived from the node's advertised
/// rate, and the seller has a right to see both figures — and the total against
/// their balance — before funding anything.
Future<CashuEscrowQuote> cashuEscrowQuote({required String orderId}) =>
    RustLib.instance.api.crateApiCashuCashuEscrowQuote(orderId: orderId);

/// Seller: fund the 2-of-3 escrow for `order_id` and submit it to the daemon.
///
/// The Cashu analogue of paying the hold invoice. In order:
///
/// 1. refuse unless the balance covers `amount + fee` — a partial lock would
///    strand the escrow amount in a token nobody can settle;
/// 2. build the escrow token (2-of-3, locktime) and, when the node charges a
///    fee, the fee token (1-of-1 to Mostro);
/// 3. publish `AddCashuEscrow`;
/// 4. persist the token against the trade **before** returning, so an app that
///    dies here can re-submit rather than lose track of locked funds.
///
/// Step 4 deliberately follows the publish: the funds are already committed at
/// the mint by step 2, so the token is worth recording even if the publish
/// failed — the daemon's own handler is idempotent on a re-submission.
///
/// **Errors** (stable markers): `CashuNotEnabled`, `CashuNotConnected`,
/// `CashuInsufficientFunds`, `CashuNodeFeeUnknown`, `NotTheSeller`,
/// plus the `CashuLockFailed` markers from token construction.
Future<CashuEscrowQuote> lockEscrow({required String orderId}) =>
    RustLib.instance.api.crateApiCashuLockEscrow(orderId: orderId);

/// Subscribe to wallet changes.
Future<CashuWalletStream> onCashuWalletChanged() =>
    RustLib.instance.api.crateApiCashuOnCashuWalletChanged();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CashuWalletStream>>
abstract class CashuWalletStream implements RustOpaqueInterface {
  /// Poll for the next wallet-changed event.
  ///
  /// A lagged receiver skips dropped snapshots: the value is current state,
  /// so only the newest one matters.
  Future<CashuWalletStatus> next();
}
